---

- include: included_play.yml

- name: no hosts match
  hosts: none

- name: do stuff
  hosts: local
  vars:
    demo_var: true
  vars_files:
    - vars/demo_vars.yml
  #vars_prompt:
  #  - name: demo_var_from_prompt
  #    prompt: enter anything you want
  pre_tasks:
    - name: include tasks from another file
      include: included_task.yml
    - name: not used
      debug: var={{item}}
      when: false
      with_items:
        - v2_runner_on_no_hosts
        - v2_runner_on_async_poll

    - name: a task
      command: uptime
      changed_when: false
    - name: a skipped task
      command: whoami
      when: false
    - name: a failed task
      action: ping
      failed_when: true
      ignore_errors: true
    - name: a task that triggers a handler
      command: uname -a
      notify: demo handler
    - name: a task with items
      command: echo {{item|string|quote}}
      with_items:
        - '{{demo_var}}'
        - '{{demo_var_from_file}}'
        #- '{{demo_var_from_prompt}}'
    - name: a task with failed items
      debug:
        msg: '{{item}}'
      with_items: [one, two, three]
      failed_when: true
      ignore_errors: true
    - name: task with retries
      shell: echo $(((RANDOM % 10) + 1))
      register: random_result
      changed_when: false
      until: random_result.stdout == "1"
      retries: 99
      delay: 1
      tags: retry
    - name: test diff
      copy:
        content: '{{lookup("pipe", "date")}}'
        dest: /tmp/{{inventory_hostname}}
      tags: diff
  roles:
    - role: demo
  handlers:
    - name: demo handler
      action: ping
